json.id review.id
json.businessId review.business_id
json.position review.position
json.startDate review.start_date
json.endDate review.end_date.to_i
json.employmentType review.employment_type
json.wage review.wage
json.tips review.tips
json.gender review.gender
json.orientation review.orientation
json.race review.race
json.notes review.notes