json.id review.id
json.position review.position
json.startDate review.start_date
json.endDate review.end_date
json.employmentType review.employment_type
json.wage review.wage
json.tips review.tips
json.gender review.gender
json.orientation review.orientation
json.race review.race